language: python

python:
  - 2.7.9

dist: jessie

install:
  - sudo apt-get -qq update
  - sudo apt-get install -y debhelper dh-autoreconf devscripts

script:
    - debuild -i -us -uc -b

after_failure:
  - cat ./Logs/sickrage.log

notifications:
  email:
    on_success: change
    on_failure: change
