language: python

python:
  - 2.7.9

dist: jessie

install:
  - sudo apt-get -qq update
  - sudo apt-get install -y debhelper dh-autoreconf devscripts

script:
    - debuild -i -us -uc -b

before_deploy:
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - git tag `dpkg-parsechangelog --show-field version` -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
  - git push -q https://$TAGPERM@github.com/Mhynlo/rn-couchpotato --tags
  - ls -R

deploy:
  skip_cleanup: true
  provider: releases
  api_key: $TAGPERM
  file: `dpkg-parsechangelog --show-field source`_`dpkg-parsechangelog --show-field version`_all.deb


notifications:
  email:
    on_success: change
    on_failure: change
